### ISSUE TITLE
App Crashes everytime I try to add new repo

### ISSUE THREAD

**Issue by Rufusdotrufus** [jroddev/android-oss-release-tracker#12]
I have a Pixel 4 running Graphene OS w/ Android ver. 13.

I downloaded the app ( ver 0.1.5) through the Neo Store.  I tried adding a few different github urls for open source apps on my phone which have github pages with package releases.  The app allows me to add url and when I click the TEST button, the app crashes.  Below find the crash report.

Thanks

type: crash
osVersion: google/flame/flame:13/TP1A.221005.002/2022113000:user/release-keys
package: com.jroddev.android_oss_release_tracker:6
process: com.jroddev.android_oss_release_tracker
processUptime: 31429 + 515 ms

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.get(ArrayList.java:437)
at com.jroddev.android_oss_release_tracker.repo.CommonRepo.getApplicationName(Repo.kt:169)
at com.jroddev.android_oss_release_tracker.repo.RepoMetaData. (Repo.kt:52)
at com.jroddev.android_oss_release_tracker.ui.NewTrackerScreenKt.TrackerPreview(NewTrackerScreen.kt:37)
at com.jroddev.android_oss_release_tracker.ui.NewTrackerScreenKt.NewTrackerScreen(NewTrackerScreen.kt:119)
at com.jroddev.android_oss_release_tracker.ui.NewTrackerScreenKt$NewTrackerScreen$2.invoke(Unknown Source:8)
at com.jroddev.android_oss_release_tracker.ui.NewTrackerScreenKt$NewTrackerScreen$2.invoke(Unknown Source:8)
at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2643)
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3260)
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3203)
at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:771)
at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1031)
at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:534)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:827)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7ec283a, androidx.compose.ui.platform.MotionDurationScaleImpl@aaafceb, StandaloneCoroutine{Cancelling}@c9f7a48, AndroidUiDispatcher@2d930e1]

```

**Comment by Rufusdotrufus** [comment]
With additional testing.  I deleted ver 0.1.5 and installed 0.1.4.  With 0.1.4 installed, I was able to add repo urls without problem.  After I installed six or seven repos, I decided to click on OSS Android from within the app and update to 0.1.5.  The app updated but every app tracked had a SHOW ERROR box.  Clicking on the box =  .com.android.volley.AuthFailureError

**Comment by jroddev** [comment]
@Rufusdotrufus can you provide a URL or two that are causing the issue? 
You can get exactly what the app is using by going Settings > Export Repo List.

Based on the error you posted sounds like the URL is shorter than I was expecting
e.g.
```
https://github.com/<org>/<app>
```
Sounds like `<app>` part may be missing.

**Comment by Rufusdotrufus** [comment]
Hi thanks for the quick response

Here is a list of the apps listed in the Export Repo List .txt file.

https://github.com/jroddev/android-oss-release-tracker
https://github.com/beemdevelopment/Aegis
https://github.com/LibreShift/red-moon
https://github.com/SimpleMobileTools/Simple-Draw
https://github.com/SimpleMobileTools/Simple-Voice-Recorder
https://github.com/SimpleMobileTools/Simple-Calendar
https://github.com/CatimaLoyalty/Android
https://github/M66B/FairEmail/releases
https://github.com/SimpleMobileTools/Simple-Notes
https://github.com/SimpleMobileTools/Simple-Flashlight

December 3, 2022 at 11:22:48 PM CET jroddev ***@***.***> wrote:

@Rufusdotrufus can you provide a URL or two that are causing the issue?
You can get exactly what the app is using by going Settings > Export Repo List.
Based on the error you posted sounds like the URL is shorter than I was expecting
e.g.https://github.com/<org>/<app>
Sounds like <app> part may be missing.

**Comment by jroddev** [comment]
OK So I think there may be two issues here.
`https://github/M66B/FairEmail/releases` is missing the `.com` which may be causing issues.

I usually see `com.android.volley.AuthFailureError` when GitHub is rate-limiting your IP address.
This is a known issue/limitation with this app at the moment - https://github.com/jroddev/android-oss-release-tracker/issues/5
You can reset the counter by changing you IP address (switch between mobile data and WiFi, or using a VPN if you have one).

Let me know it these help
