### ISSUE TITLE
App crashes when adding repository

### ISSUE THREAD

**Issue by bluefly000** [jroddev/android-oss-release-tracker#2]
When I entered the [Obtainium repository URL](https://github.com/ImranR98/Obtainium), the app crashed.

Device: Pixel6a running GrapheneOS
App version: 0.1.1

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022110800:user/release-keys
package: [com.jroddev.android](http://com.jroddev.android/)_oss_release_tracker:2
process: [com.jroddev.android](http://com.jroddev.android/)_oss_release_tracker

java.lang.Error: Error occurred parsing https://raw.githubusercontent.com/ImranR98/Obtainium/main/app/build.gradle
	at [com.jroddev.android](http://com.jroddev.android/)_oss_release_tracker.repo.CommonRepo.fetchPackageName$suspendImpl(Repo.kt:193)
	at [com.jroddev.android](http://com.jroddev.android/)_oss_release_tracker.repo.CommonRepo$fetchPackageName$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback([Handler.java:942](http://handler.java:942/))
	at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
	at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/))
	at android.os.Looper.loop([Looper.java:288](http://looper.java:288/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7904](http://activitythread.java:7904/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:548](http://runtimeinit.java:548/))
	at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:49](http://execinit.java:49/))
	at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:355](http://runtimeinit.java:355/))
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bd0b345, Dispatchers.Main]

```

**Comment by jroddev** [comment]
@bluefly000 Thanks for reporting. This is because the android root for Obtainium is `android/app` instead of `app`. Might be a Flutter convention.
I have added support for this now in [0.1.2](https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.2)

**Comment by Ilithy** [comment]
Hi and thank you very much for this excellent app, but I have a problems adding some directories...

Pixel 6 pro
Grapheneos (Android 13)
OSS Trackers version 0.1.1
Install from IzzyOnDroid

For example, that of the [Aves](https://github.com/deckerst/aves) application

```
type: crash
osVersion: google/raven/raven:13/TP1A.221005.002/2022110600:user/release-keys
package: com.jroddev.android_oss_release_tracker:2
process: com.jroddev.android_oss_release_tracker

java.lang.Error: Error occurred parsing https://raw.githubusercontent.com/deckerst/aves/develop/app/build.gradle
	at com.jroddev.android_oss_release_tracker.repo.CommonRepo.fetchPackageName$suspendImpl(Repo.kt:193)
	at com.jroddev.android_oss_release_tracker.repo.CommonRepo$fetchPackageName$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b3ba71b, Dispatchers.Main]

```

For [Octodroid](https://github.com/slapperwan/gh4a):

```
type: crash
osVersion: google/raven/raven:13/TP1A.221005.002/2022110600:user/release-keys
package: com.jroddev.android_oss_release_tracker:2
process: com.jroddev.android_oss_release_tracker

java.lang.Error: Error occurred parsing https://raw.githubusercontent.com/slapperwan/gh4a/edit-menu/app/build.gradle
	at com.jroddev.android_oss_release_tracker.repo.CommonRepo.fetchPackageName$suspendImpl(Repo.kt:172)
	at com.jroddev.android_oss_release_tracker.repo.CommonRepo$fetchPackageName$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d8ca2f8, Dispatchers.Main]

```
